import React from 'react'

function Story(){
  return(
    <>
    <h1>My Story</h1>
    <div className="story">
    <p>.Thank you for showing intrest to clink on the button to lear  I was born in a small village named Chhomrong in the mountains of Nepal. When I was old enough to attend School, my parents and I hiked for 3 days for admission to a boarding school in Pokhara, the second largest city of Nepal. My parents have a tourist hotel on a trekking route to Annapurna Base Camp; it is a hotel now, back then it used to be a teashop for climbers. I am the first one in my entire family tree to attend school and my parents worked very hard to make sure I go to one of the good ones in the city.
    </p><p>I was in 8th grade when I wrote my first program in QBASIC. We had an hour-long computer science class twice a week, Tuesdays for learning theories and Thursdays for practical. Out of the 10 subjects we studied in high school, Computer Science was my favorite one. I used to scribble BASIC code on paper throughout the week just so that I can test during my hour in front of the computer. We were not allowed to use the same computer every time and I still remember some of the computers would take about 20 minutes just to load the OS. A successful execution of interpreted code gave me a lot of joy, at the same time bugs and error messages gave me motivation and desire to figure out why it did not work. Some of the programs I wrote back then include a console version of who wants to be a millionaire, a text base shop tally program and string representing program.</p>
<p>After I graduated high school, I had to select a path- science or management. There was no option to study Computer Science or programming. I enrolled in Cambridge University’s GCE A Level Science program at Cosmos International College and graduated in the year of 2010. As soon as I cleared my A level examination, I had to follow the tradition of my family to test for becoming a Gurkha. You can click <a href="https://www.youtube.com/watch?v=O8pIJglsYUE">here</a> to learn about Gurkha. Even after passing the rigorous test 3 consecutive times, I was not the selected 0.1%. At 21 out of the age bracket to apply for Gurkha, I now started research Engineering programs.</p>
<p>With a taste of advanced curriculum and education from an international institution, outdated curriculum in Nepal’s Engineering Universities repelled me. I ended up applying to US universities and moved to San Francisco, California in 2012. As an international student, I was not allowed to work and my parents’ income from the hotel was coming short to pay for my expenses in the most expensive city in the US. In the year of 2015, I enlisted in the Army as Helicopter Mechanic. There was not a specific reason for picking this job, I joined out of necessity and that was one of the interesting jobs. Who don’t want to learn about Helicopters, specially Apache Attack helicopter? </p>
<p>After spending so much of my parents hard earned money and a lot of my own energy, I was determined to further my educaiton. As soon as I completing my initial military training, I enrolled in school again and this time into the Major of my choice. When I went trough my first programming class, everything clicked, even after so many years I could remember the concept of program flow, loops, variables etc. It was not QBASIC, but it was similar, it was Java. Attending college during active duty was not easy but driven with keen interest in computer science and desire to learn more I kept enrolling in classes after classes. Fast forward, in May of 2020 I graduated with a Bachelors of Science in Computer Science from University of Maryland Global Campus.</p>
<p>Today, I am building this website to tell you my story. With my service to this great nation, which has given me so much, coming to an end on October 4, 2021, I am constantly learning by building projects and self study. Click on projects tabs to check them out.</p>
<p>Thank you for reading my story. You can also leave me a comment or feedback using the contact me tab.</p>
</div>
</>
  )
}

export default Story;
